# Generated by Django 2.2.1 on 2021-01-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTypeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll2.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255)),
                ('option_status', models.BooleanField(blank=True, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll2.Answer')),
            ],
        ),
    ]
