# Generated by Django 2.2.1 on 2021-01-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0005_remove_answer_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertypeoption',
            name='option_status',
        ),
        migrations.DeleteModel(
            name='AnswerTypeText',
        ),
    ]
