# Generated by Django 2.2.1 on 2021-01-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0006_auto_20210125_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerTypeOption',
            new_name='AnswerOption',
        ),
    ]
