# Generated by Django 2.2.1 on 2021-01-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0010_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='AnswerBoolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
