# Generated by Django 2.2.1 on 2021-01-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0014_auto_20210125_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll2.AnswerOption'),
        ),
    ]
