# Generated by Django 2.2.1 on 2021-01-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0016_auto_20210125_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
