# Generated by Django 2.2.1 on 2021-01-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0017_auto_20210125_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT_ANSWER', 'TEXT_ANSWER'), ('ONE_OPTION_ANSWER', 'ONE_OPTION_ANSWER'), ('MANY_OPTIONS_ANSWER', 'MANY_OPTIONS_ANSWER')], default='TEXT_ANSWER', max_length=255),
        ),
    ]
