# Generated by Django 2.2.1 on 2021-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0019_auto_20210125_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT_ANSWER', 'TEXT_ANSWER'), ('MANY_OPTIONS_ANSWER', 'MANY_OPTIONS_ANSWER')], default='TEXT_ANSWER', max_length=255),
        ),
    ]
