# Generated by Django 2.2.1 on 2021-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0020_auto_20210125_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_periodic_number',
            field=models.IntegerField(default=1),
        ),
    ]
