# Generated by Django 2.2.1 on 2021-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210118_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ends',
            field=models.DateTimeField(),
        ),
    ]
