# Generated by Django 2.2.1 on 2021-01-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ends',
            new_name='date_end',
        ),
    ]
