# Generated by Django 2.2.1 on 2021-01-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210118_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_end',
        ),
    ]
