# Generated by Django 2.2.1 on 2021-01-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_date_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
