# Generated by Django 2.2.1 on 2021-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
