# Generated by Django 2.2.1 on 2021-01-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210118_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date_end',
        ),
    ]
