# Generated by Django 2.2.1 on 2021-01-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_test_date_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
