# Generated by Django 2.2.1 on 2021-01-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
