# Generated by Django 2.2.1 on 2021-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0014_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_starts', models.DateField(null=True)),
                ('date_ends', models.DateField(null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
