# Generated by Django 2.2.1 on 2021-01-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210119_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('TEXT_ANSWER', 'TEXT_ANSWER'), ('ONE_OPTION_ANSWER', 'ONE_OPTION_ANSWER'), ('MANY_OPTIONS_ANSWER', 'MANY_OPTIONS_ANSWER')], default='TEXT_ANSWER', max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll')),
            ],
        ),
    ]
