# Generated by Django 2.2.1 on 2021-01-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210119_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choice_rel', to='main.Question')),
            ],
            options={
                'verbose_name': 'Ответ с вариантом',
                'verbose_name_plural': 'Ответы с вариантом',
            },
        ),
    ]
