# Generated by Django 2.2.1 on 2021-01-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_userpoll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
