# Generated by Django 2.2.1 on 2021-01-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
