# Generated by Django 2.2.1 on 2021-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210119_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
