# Generated by Django 2.2.1 on 2021-01-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210119_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poll_rel', to='main.UserPoll'),
        ),
    ]
