# Generated by Django 2.2.1 on 2021-01-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_answer_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserPoll'),
        ),
    ]
