# Generated by Django 2.2.1 on 2021-01-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_choice_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user_poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poll_choice_rel', to='main.UserPoll'),
        ),
    ]
