# Generated by Django 2.2.1 on 2021-01-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_choice_user_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
