# Generated by Django 2.2.1 on 2021-01-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_answerwithonechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerwithonechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_option_answer', to='main.Question'),
        ),
    ]
