# Generated by Django 2.2.1 on 2021-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210120_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerwithonechoice',
            name='answered_or_no',
            field=models.BooleanField(null=True),
        ),
    ]
