# Generated by Django 2.2.1 on 2021-01-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_answerwithonechoice_answered_or_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerwithonechoice',
            name='answered_or_no',
        ),
    ]
