# Generated by Django 2.2.1 on 2021-01-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_answerwithonechoice_answered_or_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerWithManyChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_one', models.BooleanField(null=True)),
                ('vote_two', models.BooleanField(null=True)),
                ('vote_three', models.BooleanField(null=True)),
                ('vote_one_desc', models.CharField(max_length=255)),
                ('vote_two_desc', models.CharField(max_length=255)),
                ('vote_three_desc', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='many_choice_answer_poll_rel', to='main.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='many_option_answer', to='main.Question')),
                ('user_poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poll_many_choice_rel', to='main.UserPoll')),
            ],
        ),
    ]
