# Generated by Django 2.2.1 on 2021-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210120_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_starts',
            field=models.DateField(null=True),
        ),
    ]
