# Generated by Django 2.2.1 on 2021-01-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210120_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserPoll'),
        ),
    ]
