# Generated by Django 2.2.1 on 2021-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210120_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_periodic_number',
            field=models.IntegerField(default=1),
        ),
    ]
