# Generated by Django 2.2.1 on 2021-01-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_question_question_periodic_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_periodic_number',
        ),
    ]
